
name: Run CI

on:
  push:
  workflow_call:
  
permissions:
  contents: read

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.7'
    - name: Update pip
      run: |
        python -m pip install --upgrade pip
    - name: Mypy check
      run: |
        pip install mypy
        mypy --python-version 3.7 src/
    - name: Test
      run: |
        pip install pytest
        pytest src/tsidpy/*.py --doctest-modules
